### PR TITLE
Add github action sentry release workflow

### PR DESCRIPTION
**Pull request by yohang88**
Add github action sentry release workflow for adding version info on deployment.

https://docs.sentry.io/product/releases/
https://github.com/marketplace/actions/sentry-release

### CODE REVIEW

**Comment by yohang88** [comment]
@rindibudiaramdhan please check CI workflow because it's failed with message:
```
 ✘ Post request final
   │
   │ Response status code [500] is not a successful status code.
   │ Failed asserting that false is true.
   │
   │ /home/runner/work/pikobar-logistik-api/pikobar-logistik-api/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:74
   │ /home/runner/work/pikobar-logistik-api/pikobar-logistik-api/tests/Feature/LogisticRequestTest.php:289
```
I'm only update composer dependencies and add github action workflow (no code change).

**Comment by rindibudiaramdhan** [comment]
> @rindibudiaramdhan please check CI workflow because it's failed with message:
> 
> ```
>  ✘ Post request final
>    │
>    │ Response status code [500] is not a successful status code.
>    │ Failed asserting that false is true.
>    │
>    │ /home/runner/work/pikobar-logistik-api/pikobar-logistik-api/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:74
>    │ /home/runner/work/pikobar-logistik-api/pikobar-logistik-api/tests/Feature/LogisticRequestTest.php:289
> ```
> 
> I'm only update composer dependencies and add github action workflow (no code change).

no prob. this issue is on the Test Class. It should use fake HTTP to get response from other integrated System

**Review by rindibudiaramdhan — APPROVED** [review]
note:
this is action using [gothub action shot SHA](https://github.com/marketplace/actions/short-sha)

**Comment by yohang88** [comment]
Thank youuu @rindibudiaramdhan

**Pull request merged**
